Dev be -> dev
boostcampwm-2024/web17-boostproject pull request #300
Opened 2024-11-30 08:31 UTC by xjfcnfw3

close #

## ✅ 작업 내용

## 📸 스크린샷(FE만)

## 📌 이슈 사항

## 🟢 완료 조건

## ✍ 궁금한 점

## 😎 체크 사항

- [ ] label 설정 확인
- [ ] 브랜치 방향 확인

2024-11-30 13:39 UTC, swkim12345 approved these changes
dev-be에서 dev는 스쿼시 머지 안 하겠습니다..!

2024-11-30 15:29 UTC, baegyeong requested changes
성환님 pr 머지 이후로 충돌파일이 추가 된 것 같아요..!

2024-11-30 15:37 UTC, swkim12345 commented
앗...아... 내일 게더에서 실시간으로 한번 해보겠습니다

2024-12-04 18:54 UTC, swkim12345 approved these changes

2024-12-04 19:53 UTC, baegyeong approved these changes

2024-12-04 19:53 UTC, merged